#!/bin/bash

# Interactive Docker Deployment
# Config tất cả qua prompts, không cần edit files

set -e

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${BLUE}🐳 Discord PDF - Interactive Docker Deploy${NC}"
echo "==============================================="
echo ""

# Check Docker
if ! command -v docker &> /dev/null; then
    echo -e "${RED}❌ Docker not found${NC}"
    echo "Install Docker:"
    echo "  curl -fsSL https://get.docker.com -o get-docker.sh"
    echo "  sudo sh get-docker.sh"
    exit 1
fi

if ! command -v docker-compose &> /dev/null; then
    echo -e "${RED}❌ Docker Compose not found${NC}"
    exit 1
fi

# Prompt for configuration
echo -e "${YELLOW}Enter Configuration:${NC}"
echo ""

read -p "Discord Client ID: " DISCORD_CLIENT_ID
if [ -z "$DISCORD_CLIENT_ID" ]; then
    echo -e "${RED}❌ Discord Client ID is required${NC}"
    exit 1
fi

read -p "Discord Client Secret: " DISCORD_CLIENT_SECRET
if [ -z "$DISCORD_CLIENT_SECRET" ]; then
    echo -e "${RED}❌ Discord Client Secret is required${NC}"
    exit 1
fi

echo ""
read -p "Frontend Port [8080]: " FRONTEND_PORT
FRONTEND_PORT=${FRONTEND_PORT:-8080}

read -p "Backend Port [3001]: " BACKEND_PORT
BACKEND_PORT=${BACKEND_PORT:-3001}

read -p "Your VPS IP or Domain: " DOMAIN
if [ -z "$DOMAIN" ]; then
    echo -e "${RED}❌ Domain/IP is required${NC}"
    exit 1
fi

read -p "Max PDF Upload Size in MB [50]: " MAX_SIZE_MB
MAX_SIZE_MB=${MAX_SIZE_MB:-50}
MAX_FILE_SIZE=$((MAX_SIZE_MB * 1024 * 1024))

# Summary
echo ""
echo -e "${YELLOW}Configuration Summary:${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Discord Client ID: ${DISCORD_CLIENT_ID:0:20}..."
echo "  Frontend: http://$DOMAIN:$FRONTEND_PORT"
echo "  Backend:  http://$DOMAIN:$BACKEND_PORT"
echo "  Max Upload: ${MAX_SIZE_MB}MB"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
read -p "Continue with deployment? [y/N] " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    exit 1
fi

# Create .env file for docker-compose
echo ""
echo -e "${BLUE}Creating .env file...${NC}"

cat > .env <<EOF
# Auto-generated by docker-deploy-interactive.sh
# Generated: $(date)

DISCORD_CLIENT_ID=$DISCORD_CLIENT_ID
DISCORD_CLIENT_SECRET=$DISCORD_CLIENT_SECRET

NODE_ENV=production

FRONTEND_PORT=$FRONTEND_PORT
BACKEND_PORT=$BACKEND_PORT

DOMAIN=$DOMAIN
VITE_BACKEND_URL=http://$DOMAIN:$BACKEND_PORT
VITE_BACKEND_WS_URL=ws://$DOMAIN:$BACKEND_PORT
CORS_ORIGIN=http://$DOMAIN:$FRONTEND_PORT

MAX_FILE_SIZE=$MAX_FILE_SIZE
EOF

echo "✓ .env file created"

# Build and deploy
echo ""
echo -e "${BLUE}Building Docker images...${NC}"
docker-compose -f docker-compose.env.yml build

echo ""
echo -e "${BLUE}Starting containers...${NC}"
docker-compose -f docker-compose.env.yml up -d

echo ""
echo -e "${GREEN}✅ Deployment Complete!${NC}"
echo ""
echo "Access your app:"
echo "  Frontend: http://$DOMAIN:$FRONTEND_PORT"
echo "  Backend:  http://$DOMAIN:$BACKEND_PORT/health"
echo ""
echo "Docker commands:"
echo "  docker-compose -f docker-compose.env.yml ps       - Status"
echo "  docker-compose -f docker-compose.env.yml logs -f  - Logs"
echo "  docker-compose -f docker-compose.env.yml restart  - Restart"
echo "  docker-compose -f docker-compose.env.yml down     - Stop"
echo ""
echo -e "${YELLOW}⚠️  Next steps:${NC}"
echo ""
echo "1. Configure firewall:"
echo "   sudo ufw allow $FRONTEND_PORT/tcp"
echo "   sudo ufw allow $BACKEND_PORT/tcp"
echo ""
echo "2. Update Discord Activity URL Mapping:"
echo "   Discord Portal → Activities → URL Mappings"
echo "   Prefix: /.proxy"
echo "   Target: http://$DOMAIN:$FRONTEND_PORT"
echo ""
echo "3. Test deployment:"
echo "   curl http://$DOMAIN:$BACKEND_PORT/health"
echo "   curl http://$DOMAIN:$FRONTEND_PORT"
echo ""
echo "4. Upload limit is ${MAX_SIZE_MB}MB"
echo "   To change, edit .env file and restart:"
echo "   nano .env  # Change MAX_FILE_SIZE"
echo "   docker-compose -f docker-compose.env.yml restart"
